# --- Identification du projet ---
sonar.projectKey=efrei-api-crisiview
sonar.projectName=EFREI - Crisiview API
sonar.projectVersion=1.0

# --- Chemins des sources ---
sonar.sources=.
sonar.sourceEncoding=UTF-8

# --- Configuration du Coverage (Lien avec Jest) ---
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# --- Exclusions ---
sonar.exclusions=**/node_modules/**, **/__tests__/**, coverage/**, jest.config.js, babel.config.js, .env.example

# --- Tests ---
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.js

# --- Type de code ---
sonar.language=js
sonar.javascript.environments=node